on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: IbzanHyena/setup-j@v1
        with:
          j-version: "903"
      - name: Install relimport
        run: |
          # Find ~Projects directory to clone into
          PROJ=$(ijconsole -js "echo jpath '~Projects'" "exit''")
          pushd "$PROJ"
          git clone https://github.com/IbzanHyena/relimport.git
          popd
      - name: Build site
        run: |
          ijconsole blog/run.ijs .
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog-ibzan-co-uk
          directory: _site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

